name: Update pics used in README.md
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 * * * *"
jobs:
  update-pics:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Update pics
        env:
          POLYGON: ${{ secrets.POLYGON }}
        run: |
          # Generate default chart (365 days with default tickers)
          python github_actions.py
          sleep 1m # pause because of API restrictions
          
          # Generate 3-day chart with default tickers
          python github_actions.py 3
          sleep 1m
          
          # Generate 14-day chart with default tickers
          python github_actions.py 14
          sleep 1m
          
          # Generate mixed portfolio chart (Polygon + CoinGecko)
          # X:BTCUSD (Polygon) + BTC ETH (CoinGecko) + X:GOOG X:NVDA (Polygon)
          python github_actions.py 365 X:BTCUSD BTC ETH X:GOOG X:NVDA
          
          # Generate crypto-only chart (CoinGecko)
          python github_actions.py 30 BTC ETH SOL ADA DOT
          
          # Generate stock-only chart (Polygon)
          python github_actions.py 90 X:GOOG X:AAPL X:NVDA X:MSFT
      - name: Check if last commit is chore commit
        id: check-commit
        run: |
          # Get the last commit message
          LAST_COMMIT_MSG=$(git log -1 --pretty=%B | head -1)
          echo "Last commit message: '$LAST_COMMIT_MSG'"
          
          # Check if it's a chore commit (autopublish)
          if [[ "$LAST_COMMIT_MSG" == *"chore: autopublish"* ]]; then
            echo "is_chore=true" >> $GITHUB_OUTPUT
            echo "Last commit is an autopublish chore commit, will amend"
          else
            echo "is_chore=false" >> $GITHUB_OUTPUT
            echo "Last commit is not a chore commit, will create new commit"
          fi
          
          # Log current git status for debugging
          echo "Current git status:"
          git status --porcelain
      - name: Amend last commit if it's a chore commit
        if: steps.check-commit.outputs.is_chore == 'true'
        run: |
          # Configure git user for CI
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Check if there are actually changes to commit
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "No changes detected, skipping commit"
            exit 0
          fi
          
          # Add all changes
          git add -A
          
          # Show what will be committed
          echo "Changes to be committed:"
          git status --porcelain
          
          # Amend the last commit without changing the message
          git commit --amend --no-edit
          
          # Force push with lease for safety
          git push --force-with-lease origin main
          
          echo "Successfully amended the last chore commit"
      - name: Create new commit if not a chore commit
        if: steps.check-commit.outputs.is_chore == 'false'
        uses: actions-js/push@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
