name: Update pics used in README.md
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 * * * *"
jobs:
  update-pics:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Update pics
        env:
          POLYGON: ${{ secrets.POLYGON }}
          COIN_GECKO: ${{ secrets.COIN_GECKO }}
        run: |
          # Generate default chart (365 days with default tickers)
          python github_actions.py
          
          # Generate 3-day chart with default tickers
          python github_actions.py 3
          
          # Generate 14-day chart with default tickers
          python github_actions.py 14

          # BTC and Major Stocks (using reliable Polygon tickers)
          python github_actions.py 365 BTC X:GOOG X:NVDA X:AAPL X:MSFT

      - name: Check if last commit is chore commit
        id: check-commit
        run: |
          # Get the last commit message
          LAST_COMMIT_MSG=$(git log -1 --pretty=%B | head -1)
          echo "Last commit message: '$LAST_COMMIT_MSG'"
          
          # Check if it's a chore commit (autopublish)
          if [[ "$LAST_COMMIT_MSG" == *"chore: autopublish"* ]]; then
            echo "is_chore=true" >> $GITHUB_OUTPUT
            echo "Last commit is an autopublish chore commit, will amend"
          else
            echo "is_chore=false" >> $GITHUB_OUTPUT
            echo "Last commit is not a chore commit, will create new commit"
          fi
          
          # Log current git status for debugging
          echo "Current git status:"
          git status --porcelain
      - name: Amend last commit if it's a chore commit
        if: steps.check-commit.outputs.is_chore == 'true'
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          amend: true
          force: true
      - name: Create new commit if not a chore commit
        if: steps.check-commit.outputs.is_chore == 'false'
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

